backend:
  name: github
  repo: labroute/labroute.github.io   # Reemplaza TU_USUARIO por tu usuario real de GitHub
  branch: main
  base_url: https://bejewelled-salmiakki-da1537.netlify.app  # URL de tu sitio en Netlify
  auth_endpoint: /.netlify/functions/auth

media_folder: "static/img"        # Carpeta donde se guardarán las imágenes
public_folder: "/static/img"      # Ruta pública para acceder a las imágenes

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "articulos/contenido"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
