backend:
  name: github
  repo: labroute/labroute.github.io   # Reemplaza TU_USUARIO por tu usuario real de GitHub
  branch: main
  base_url: https://bejewelled-salmiakki-da1537.netlify.app  # URL de tu sitio en Netlify
  auth_endpoint: /.netlify/functions/auth

media_folder: "static/img"        # Carpeta donde se guardarán las imágenes
public_folder: "/static/img"      # Ruta pública para acceder a las imágenes

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "articulos/contenido"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Categoría", name: "category", widget: "select", options: ["Penetration Testing","Network Security","Threat Hunting","Automation","OSINT","Malware Analysis"] }
      - { label: "Dificultad", name: "difficulty", widget: "select", options: ["Principiante","Intermedio","Avanzado"] }
      - { label: "Tiempo de lectura (min)", name: "reading_time", widget: "number", required: false }
      - { label: "Imagen de portada (opcional)", name: "cover", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
